128 add new atributes to stock model
Lv-581-Python-project/StockDashboard pull request #146
Opened 2021-05-17 17:01 UTC by OstapOmelchuk

2021-05-17 19:43 UTC, daniiloleshchuk requested changes

2021-05-17 19:43 UTC, daniiloleshchuk commented on stock_dashboard_api/models/dashboard_model.py
> +                print(error)
remove print

2021-05-17 19:43 UTC, daniiloleshchuk commented on stock_dashboard_api/models/stock_model.py
> +git
what??? =)))))))

2021-05-18 08:25 UTC, lhalam approved these changes

2021-05-18 11:35 UTC, lurak approved these changes

2021-05-18 11:39 UTC, daniiloleshchuk approved these changes

2021-05-18 17:12 UTC, merged