Feature/#7
Lv-581-Python-project/StockDashboard pull request #16
Opened 2021-03-28 14:29 UTC by SLDem

2021-03-28 17:59 UTC, lurak approved these changes

2021-03-29 08:59 UTC, lhalam requested changes
move to folder worker/email_sender
use SMTP lib

2021-03-29 08:59 UTC, lhalam commented on StockDashboardAPI/__init__.py
> +))
move to env

2021-03-29 08:59 UTC, lhalam commented on StockDashboardAPI/__init__.py
>  from flask import Flask
move to workers

2021-03-29 08:59 UTC, lhalam commented on StockDashboardAPI/rabbit/rabbit_channel.py
> +    rabbitmq = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
`'localhost'` use env

2021-03-29 08:59 UTC, lhalam commented on StockDashboardAPI/rabbit/rabbit_worker.py
> +                  sender='stockdashboard581@gmail.com',
use env

2021-03-29 08:59 UTC, lhalam commented on StockDashboardAPI/rabbit/rabbit_worker.py
> +channel.start_consuming()
move to __name__ ==  main

2021-03-30 10:00 UTC, daniiloleshchuk approved these changes

2021-03-30 14:27 UTC, closed without merging